var types= {

  START_GAME: "START_GAME",
  PLAYER_MOVE: "PLAYER_MOVE",
  SELECT_PIECE: "SELECT_PIECE",
  PLACE_PIECE: "PLACE_PIECE",
  UNDO_MOVE: "UNDO_MOVE",
  FINISH_MOVE: "FINISH_MOVE",
  NAME_CHANGE: "NAME_CHANGE",
  SAVE_NAME: "SAVE_NAME",
  CREATE_GAME: "CREATE_GAME",
  GAME_CREATED: "GAME_CREATED",
  MOVE_UNDONE: "MOVE_UNDONE",
  GET_AWAITING_GAMES: "GET_AWAITING_GAMES",
  GAMES_AWAITING: "GAMES_AWAITING",
  PIECE_SELECTED: "PIECE_SELECTED",
  PLAYER_MOVED: "PLAYER_MOVED",
  MOVE_FINISHED: "MOVE_FINISHED",
  JOIN_GAME:"JOIN_GAME"
}


module.exports  = types;
